name: DevOps CI Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  validate-code:
    runs-on: ubuntu-latest

    steps:
    # 1. משיכת הקוד מה-Repository
    - name: Checkout repository code
      uses: actions/checkout@v3

    # 2. בדיקת זמינות Docker במכונת ה-CI
    - name: Check Docker installation
      run: docker --version

    # 3. בדיקת תקינות קובץ ה-Dockerfile
    - name: Validate Dockerfile syntax
      run: |
        if [ -f my-custome-image/Dockerfile ]; then
          echo "Dockerfile exists and is ready for build!"
        else
          echo "Dockerfile missing!"
          exit 1
        fi

    # 4. בדיקת תקינות מבנית לקובץ ה-Kubernetes YAML
    - name: Validate Kubernetes Manifests Syntax
      run: |
        python3 -c "import yaml; yaml.safe_load(open('k8s-lab1/deployment.yaml'))"
        echo "Kubernetes YAML syntax is valid!"
